// Code generated by mockery v2.53.2. DO NOT EDIT.

package storagemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	v1 "github.com/aevon-lab/project-aevon/internal/api/v1"
)

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

type EventStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EventStore) EXPECT() *EventStore_Expecter {
	return &EventStore_Expecter{mock: &_m.Mock}
}

// RetrieveEventsAfter provides a mock function with given fields: ctx, afterTime, limit
func (_m *EventStore) RetrieveEventsAfter(ctx context.Context, afterTime time.Time, limit int) ([]*v1.Event, error) {
	ret := _m.Called(ctx, afterTime, limit)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveEventsAfter")
	}

	var r0 []*v1.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]*v1.Event, error)); ok {
		return rf(ctx, afterTime, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []*v1.Event); ok {
		r0 = rf(ctx, afterTime, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, afterTime, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_RetrieveEventsAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveEventsAfter'
type EventStore_RetrieveEventsAfter_Call struct {
	*mock.Call
}

// RetrieveEventsAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - afterTime time.Time
//   - limit int
func (_e *EventStore_Expecter) RetrieveEventsAfter(ctx interface{}, afterTime interface{}, limit interface{}) *EventStore_RetrieveEventsAfter_Call {
	return &EventStore_RetrieveEventsAfter_Call{Call: _e.mock.On("RetrieveEventsAfter", ctx, afterTime, limit)}
}

func (_c *EventStore_RetrieveEventsAfter_Call) Run(run func(ctx context.Context, afterTime time.Time, limit int)) *EventStore_RetrieveEventsAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *EventStore_RetrieveEventsAfter_Call) Return(_a0 []*v1.Event, _a1 error) *EventStore_RetrieveEventsAfter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_RetrieveEventsAfter_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]*v1.Event, error)) *EventStore_RetrieveEventsAfter_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveEventsByPrincipalAndIngestedRange provides a mock function with given fields: ctx, principalID, startIngestedAt, endIngestedAt, limit
func (_m *EventStore) RetrieveEventsByPrincipalAndIngestedRange(ctx context.Context, principalID string, startIngestedAt time.Time, endIngestedAt time.Time, limit int) ([]*v1.Event, error) {
	ret := _m.Called(ctx, principalID, startIngestedAt, endIngestedAt, limit)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveEventsByPrincipalAndIngestedRange")
	}

	var r0 []*v1.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int) ([]*v1.Event, error)); ok {
		return rf(ctx, principalID, startIngestedAt, endIngestedAt, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int) []*v1.Event); ok {
		r0 = rf(ctx, principalID, startIngestedAt, endIngestedAt, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, principalID, startIngestedAt, endIngestedAt, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveEventsByPrincipalAndIngestedRange'
type EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call struct {
	*mock.Call
}

// RetrieveEventsByPrincipalAndIngestedRange is a helper method to define mock.On call
//   - ctx context.Context
//   - principalID string
//   - startIngestedAt time.Time
//   - endIngestedAt time.Time
//   - limit int
func (_e *EventStore_Expecter) RetrieveEventsByPrincipalAndIngestedRange(ctx interface{}, principalID interface{}, startIngestedAt interface{}, endIngestedAt interface{}, limit interface{}) *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call {
	return &EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call{Call: _e.mock.On("RetrieveEventsByPrincipalAndIngestedRange", ctx, principalID, startIngestedAt, endIngestedAt, limit)}
}

func (_c *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call) Run(run func(ctx context.Context, principalID string, startIngestedAt time.Time, endIngestedAt time.Time, limit int)) *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time), args[4].(int))
	})
	return _c
}

func (_c *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call) Return(_a0 []*v1.Event, _a1 error) *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time, int) ([]*v1.Event, error)) *EventStore_RetrieveEventsByPrincipalAndIngestedRange_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveEventsAfterCursor provides a mock function with given fields: ctx, cursor, limit
func (_m *EventStore) RetrieveEventsAfterCursor(ctx context.Context, cursor int64, limit int) ([]*v1.Event, error) {
	ret := _m.Called(ctx, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveEventsAfterCursor")
	}

	var r0 []*v1.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]*v1.Event, error)); ok {
		return rf(ctx, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []*v1.Event); ok {
		r0 = rf(ctx, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_RetrieveEventsAfterCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveEventsAfterCursor'
type EventStore_RetrieveEventsAfterCursor_Call struct {
	*mock.Call
}

// RetrieveEventsAfterCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor int64
//   - limit int
func (_e *EventStore_Expecter) RetrieveEventsAfterCursor(ctx interface{}, cursor interface{}, limit interface{}) *EventStore_RetrieveEventsAfterCursor_Call {
	return &EventStore_RetrieveEventsAfterCursor_Call{Call: _e.mock.On("RetrieveEventsAfterCursor", ctx, cursor, limit)}
}

func (_c *EventStore_RetrieveEventsAfterCursor_Call) Run(run func(ctx context.Context, cursor int64, limit int)) *EventStore_RetrieveEventsAfterCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int))
	})
	return _c
}

func (_c *EventStore_RetrieveEventsAfterCursor_Call) Return(_a0 []*v1.Event, _a1 error) *EventStore_RetrieveEventsAfterCursor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_RetrieveEventsAfterCursor_Call) RunAndReturn(run func(context.Context, int64, int) ([]*v1.Event, error)) *EventStore_RetrieveEventsAfterCursor_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveScopedEventsAfterCursor provides a mock function with given fields: ctx, cursor, principalID, eventType, startOccurredAt, endOccurredAt, limit
func (_m *EventStore) RetrieveScopedEventsAfterCursor(ctx context.Context, cursor int64, principalID string, eventType string, startOccurredAt time.Time, endOccurredAt time.Time, limit int) ([]*v1.Event, error) {
	ret := _m.Called(ctx, cursor, principalID, eventType, startOccurredAt, endOccurredAt, limit)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveScopedEventsAfterCursor")
	}

	var r0 []*v1.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, time.Time, time.Time, int) ([]*v1.Event, error)); ok {
		return rf(ctx, cursor, principalID, eventType, startOccurredAt, endOccurredAt, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, time.Time, time.Time, int) []*v1.Event); ok {
		r0 = rf(ctx, cursor, principalID, eventType, startOccurredAt, endOccurredAt, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, time.Time, time.Time, int) error); ok {
		r1 = rf(ctx, cursor, principalID, eventType, startOccurredAt, endOccurredAt, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventStore_RetrieveScopedEventsAfterCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveScopedEventsAfterCursor'
type EventStore_RetrieveScopedEventsAfterCursor_Call struct {
	*mock.Call
}

// RetrieveScopedEventsAfterCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor int64
//   - principalID string
//   - eventType string
//   - startOccurredAt time.Time
//   - endOccurredAt time.Time
//   - limit int
func (_e *EventStore_Expecter) RetrieveScopedEventsAfterCursor(ctx interface{}, cursor interface{}, principalID interface{}, eventType interface{}, startOccurredAt interface{}, endOccurredAt interface{}, limit interface{}) *EventStore_RetrieveScopedEventsAfterCursor_Call {
	return &EventStore_RetrieveScopedEventsAfterCursor_Call{Call: _e.mock.On("RetrieveScopedEventsAfterCursor", ctx, cursor, principalID, eventType, startOccurredAt, endOccurredAt, limit)}
}

func (_c *EventStore_RetrieveScopedEventsAfterCursor_Call) Run(run func(ctx context.Context, cursor int64, principalID string, eventType string, startOccurredAt time.Time, endOccurredAt time.Time, limit int)) *EventStore_RetrieveScopedEventsAfterCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string), args[4].(time.Time), args[5].(time.Time), args[6].(int))
	})
	return _c
}

func (_c *EventStore_RetrieveScopedEventsAfterCursor_Call) Return(_a0 []*v1.Event, _a1 error) *EventStore_RetrieveScopedEventsAfterCursor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EventStore_RetrieveScopedEventsAfterCursor_Call) RunAndReturn(run func(context.Context, int64, string, string, time.Time, time.Time, int) ([]*v1.Event, error)) *EventStore_RetrieveScopedEventsAfterCursor_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvent provides a mock function with given fields: ctx, event
func (_m *EventStore) SaveEvent(ctx context.Context, event *v1.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventStore_SaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvent'
type EventStore_SaveEvent_Call struct {
	*mock.Call
}

// SaveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *v1.Event
func (_e *EventStore_Expecter) SaveEvent(ctx interface{}, event interface{}) *EventStore_SaveEvent_Call {
	return &EventStore_SaveEvent_Call{Call: _e.mock.On("SaveEvent", ctx, event)}
}

func (_c *EventStore_SaveEvent_Call) Run(run func(ctx context.Context, event *v1.Event)) *EventStore_SaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Event))
	})
	return _c
}

func (_c *EventStore_SaveEvent_Call) Return(_a0 error) *EventStore_SaveEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventStore_SaveEvent_Call) RunAndReturn(run func(context.Context, *v1.Event) error) *EventStore_SaveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventStore creates a new instance of EventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventStore {
	mock := &EventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
