// Code generated by mockery v2.53.2. DO NOT EDIT.

package aggregationmocks

import (
	context "context"

	aggregation "github.com/aevon-lab/project-aevon/internal/core/aggregation"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PreAggregateStore is an autogenerated mock type for the PreAggregateStore type
type PreAggregateStore struct {
	mock.Mock
}

type PreAggregateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PreAggregateStore) EXPECT() *PreAggregateStore_Expecter {
	return &PreAggregateStore_Expecter{mock: &_m.Mock}
}

// Flush provides a mock function with given fields: ctx, aggregates, cursor, bucketSize
func (_m *PreAggregateStore) Flush(ctx context.Context, aggregates map[aggregation.AggregateKey]aggregation.AggregateState, cursor int64, bucketSize string) error {
	ret := _m.Called(ctx, aggregates, cursor, bucketSize)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[aggregation.AggregateKey]aggregation.AggregateState, int64, string) error); ok {
		r0 = rf(ctx, aggregates, cursor, bucketSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreAggregateStore_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type PreAggregateStore_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregates map[aggregation.AggregateKey]aggregation.AggregateState
//   - cursor int64
//   - bucketSize string
func (_e *PreAggregateStore_Expecter) Flush(ctx interface{}, aggregates interface{}, cursor interface{}, bucketSize interface{}) *PreAggregateStore_Flush_Call {
	return &PreAggregateStore_Flush_Call{Call: _e.mock.On("Flush", ctx, aggregates, cursor, bucketSize)}
}

func (_c *PreAggregateStore_Flush_Call) Run(run func(ctx context.Context, aggregates map[aggregation.AggregateKey]aggregation.AggregateState, cursor int64, bucketSize string)) *PreAggregateStore_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[aggregation.AggregateKey]aggregation.AggregateState), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *PreAggregateStore_Flush_Call) Return(_a0 error) *PreAggregateStore_Flush_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreAggregateStore_Flush_Call) RunAndReturn(run func(context.Context, map[aggregation.AggregateKey]aggregation.AggregateState, int64, string) error) *PreAggregateStore_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// LoadAggregates provides a mock function with given fields: ctx
func (_m *PreAggregateStore) LoadAggregates(ctx context.Context) (map[aggregation.AggregateKey]aggregation.AggregateState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAggregates")
	}

	var r0 map[aggregation.AggregateKey]aggregation.AggregateState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[aggregation.AggregateKey]aggregation.AggregateState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[aggregation.AggregateKey]aggregation.AggregateState); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[aggregation.AggregateKey]aggregation.AggregateState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreAggregateStore_LoadAggregates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAggregates'
type PreAggregateStore_LoadAggregates_Call struct {
	*mock.Call
}

// LoadAggregates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PreAggregateStore_Expecter) LoadAggregates(ctx interface{}) *PreAggregateStore_LoadAggregates_Call {
	return &PreAggregateStore_LoadAggregates_Call{Call: _e.mock.On("LoadAggregates", ctx)}
}

func (_c *PreAggregateStore_LoadAggregates_Call) Run(run func(ctx context.Context)) *PreAggregateStore_LoadAggregates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PreAggregateStore_LoadAggregates_Call) Return(_a0 map[aggregation.AggregateKey]aggregation.AggregateState, _a1 error) *PreAggregateStore_LoadAggregates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreAggregateStore_LoadAggregates_Call) RunAndReturn(run func(context.Context) (map[aggregation.AggregateKey]aggregation.AggregateState, error)) *PreAggregateStore_LoadAggregates_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRange provides a mock function with given fields: ctx, tenantID, principalID, ruleName, bucketSize, startTime, endTime
func (_m *PreAggregateStore) QueryRange(ctx context.Context, tenantID string, principalID string, ruleName string, bucketSize string, startTime time.Time, endTime time.Time) ([]aggregation.AggregateState, error) {
	ret := _m.Called(ctx, tenantID, principalID, ruleName, bucketSize, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for QueryRange")
	}

	var r0 []aggregation.AggregateState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, time.Time, time.Time) ([]aggregation.AggregateState, error)); ok {
		return rf(ctx, tenantID, principalID, ruleName, bucketSize, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, time.Time, time.Time) []aggregation.AggregateState); ok {
		r0 = rf(ctx, tenantID, principalID, ruleName, bucketSize, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]aggregation.AggregateState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, tenantID, principalID, ruleName, bucketSize, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreAggregateStore_QueryRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRange'
type PreAggregateStore_QueryRange_Call struct {
	*mock.Call
}

// QueryRange is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - principalID string
//   - ruleName string
//   - bucketSize string
//   - startTime time.Time
//   - endTime time.Time
func (_e *PreAggregateStore_Expecter) QueryRange(ctx interface{}, tenantID interface{}, principalID interface{}, ruleName interface{}, bucketSize interface{}, startTime interface{}, endTime interface{}) *PreAggregateStore_QueryRange_Call {
	return &PreAggregateStore_QueryRange_Call{Call: _e.mock.On("QueryRange", ctx, tenantID, principalID, ruleName, bucketSize, startTime, endTime)}
}

func (_c *PreAggregateStore_QueryRange_Call) Run(run func(ctx context.Context, tenantID string, principalID string, ruleName string, bucketSize string, startTime time.Time, endTime time.Time)) *PreAggregateStore_QueryRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(time.Time), args[6].(time.Time))
	})
	return _c
}

func (_c *PreAggregateStore_QueryRange_Call) Return(_a0 []aggregation.AggregateState, _a1 error) *PreAggregateStore_QueryRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreAggregateStore_QueryRange_Call) RunAndReturn(run func(context.Context, string, string, string, string, time.Time, time.Time) ([]aggregation.AggregateState, error)) *PreAggregateStore_QueryRange_Call {
	_c.Call.Return(run)
	return _c
}

// ReadCheckpoint provides a mock function with given fields: ctx, bucketSize
func (_m *PreAggregateStore) ReadCheckpoint(ctx context.Context, bucketSize string) (int64, error) {
	ret := _m.Called(ctx, bucketSize)

	if len(ret) == 0 {
		panic("no return value specified for ReadCheckpoint")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, bucketSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, bucketSize)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bucketSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreAggregateStore_ReadCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCheckpoint'
type PreAggregateStore_ReadCheckpoint_Call struct {
	*mock.Call
}

// ReadCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketSize string
func (_e *PreAggregateStore_Expecter) ReadCheckpoint(ctx interface{}, bucketSize interface{}) *PreAggregateStore_ReadCheckpoint_Call {
	return &PreAggregateStore_ReadCheckpoint_Call{Call: _e.mock.On("ReadCheckpoint", ctx, bucketSize)}
}

func (_c *PreAggregateStore_ReadCheckpoint_Call) Run(run func(ctx context.Context, bucketSize string)) *PreAggregateStore_ReadCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PreAggregateStore_ReadCheckpoint_Call) Return(_a0 int64, _a1 error) *PreAggregateStore_ReadCheckpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreAggregateStore_ReadCheckpoint_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *PreAggregateStore_ReadCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreAggregateStore creates a new instance of PreAggregateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreAggregateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreAggregateStore {
	mock := &PreAggregateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
